version = "2.5.2"
# maxColumn = 120
# align = most
# newlines.alwaysBeforeTopLevelStatements = true

maxColumn = 120
assumeStandardLibraryStripMargin = true

newlines.alwaysBeforeTopLevelStatements = true

rewrite.rules = [
  RedundantBraces,
  SortModifiers,
  SortImports,
  PreferCurlyFors,
  RedundantParens
]